--drop table AspNetUserRoles
--drop table AspNetUserLogins
--drop table AspNetUserClaims
--drop table AspNetUserTokens
--drop table AspNetUsers
--drop table AspNetRoleClaims
--drop table AspNetRoles
--drop table __EFMigrationsHistory